name: Taylor's Mission
favicon: null
layout_spectrum: 0.0009
typography_spectrum: 0.17163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#694932'
    - '#2c261a'
    - '#cd855f'
    - '#a56c4e'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
