name: "Taylor's Mission"
favicon: null
layout_spectrum: 0.2412
typography_spectrum: 0.73495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#694932'
    - '#2c261a'
    - '#cd855f'
    - '#a56c4e'
  brandStrength: 0.0625
  lightness: 0.028388673439621925
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
